### PR TITLE
test: initial commit adding hypothesis property testing library

### PR DESCRIPTION
**Pull request by bpshaver**
Adding the Hypothesis cache dir to .gitignore
Grammar fixes in geometry.py
Hypothesis dep in pyproject.toml without version peg Initial strategies in conftest.py. This is the only file name I could use that didn't cause an issue with the name-tests-test pre-commit hook. 'strategies.py' would be better because strictly speaking these aren't fixtures. An example test for encode/decode invariance.

### CODE REVIEW

**Comment by cleder** [comment]
I would prefer another file layout and not putting the strategies in `conftests` and keeping the hypothesis tests separate from the *classic* unit tests:

- `tests`
    - `test_point.py`
    - `test_linestring.py` 
    - ...
    - `hypothesis`
        - `__init__.py`
        - `strategies.py`
        - `test_point.py`
        - ...

The SRS could be defined as a `dataclass` like

```
@dataclass(frozen=True)
class Srs:
    name: str
    min_xyz : Tuple[float, float, Optional[float]]
    max_xyz : Tuple[float, float, Optional[float]]     
```

an instance of an srs can optionally be passed into the `points`, `points_2d`, `points_3d` strategies, if none is provided there would be no `max_value`, `min_value`set for the `st.floats` 

```
def points_3d(draw, srs: Optional[Srs]):
       ...
```
and 
```
def points_2d(draw, srs: Optional[Srs]):
     easting = (None, None)
     northing = (None, None)
     elevation = (None, None)
     if srs:
         easting = (srs.min_xyz[0], srs.max_xyz[0]
         ...
```

```
epsg4326 = Srs(name="EPSG:4326", min_xyz =(-90, 0, None), max_xyz=(90, 180, None)
```

Hope that helps :+1:  nice work

**Comment by cleder** [comment]
I would prefer another file layout and not putting the strategies in `conftests` and keeping the hypothesis tests separate from the *classic* unit tests:

- `tests`
    - `test_point.py`
    - `test_linestring.py` 
    - ...
    - `hypothesis`
        - `__init__.py`
        - `strategies.py`
        - `test_point.py`
        - ...

The SRS could be defined as a `dataclass` like

```
@dataclass(frozen=True)
class Srs:
    name: str
    min_xyz : Tuple[float, float, Optional[float]]
    max_xyz : Tuple[float, float, Optional[float]]     
```

an instance of an srs can optionally be passed into the `points`, `points_2d`, `points_3d` strategies, if none is provided there would be no `max_value`, `min_value`set for the `st.floats` 

```
def points_3d(draw, srs: Optional[Srs]):
       ...
```
and 
```
def points_2d(draw, srs: Optional[Srs]):
     easting = (None, None)
     northing = (None, None)
     elevation = (None, None)
     if srs:
         easting = (srs.min_xyz[0], srs.max_xyz[0]
         ...
```

```
epsg4326 = Srs(name="EPSG:4326", min_xyz =(-90, 0, None), max_xyz=(90, 180, None)
```

Hope that helps :+1:  nice work

**Comment by cleder** [comment]
You can add an 'exclude' to the ` name-tests-test` `pre-commit` hook in `.pre-commit-config.yaml`
```
      - id: name-tests-test
        exclude: ^tests/hypothesis/strategies.py$
```

**Comment by cleder** [comment]
Are you still working on this?

**Comment by bpshaver** [comment]
Hi, sorry. Will try and get to this tomorrow. But if you want to press on ahead I won't be offended if you remove me from this issue.

**Comment by cleder** [comment]
@CodiumAI /describe

**Comment by cleder** [comment]
@CodiumAI-Agent /review

**Comment by cleder** [comment]
@CodiumAI-Agent /improve

**Comment by cleder** [comment]
you may be interested in #219 or #220 ;-)

**Pull request merged**
