### PR TITLE
Add informative __repr__ for _Feature

### PR DESCRIPTION
**Pull request by johnpdees**
Created __repr__ method for geometry types:  Point, LineString,
LinearRing, Polygon, Multipoint, MultiLineString, MultiPolygon,
GeometryCollection, and _type = None cases.

The intent of the modification is to have __repr__ return informative
string. For example, __repr__ for LineString instance will return instance
type and the number of coordinate sets associated with the object. The
__repr__ for a Point instance will return a string that allows rebuilding
of the object.

Added test_suite to verify output of geometry __repr__ calls.

### CODE REVIEW

**Comment by cleder** [comment]
https://travis-ci.org/cleder/pygeoif/jobs/52157950

can you ensure pep8 compliance and fix that one failing test?

**Comment by johnpdees** [comment]
The main test failure has been fixed. However, I am still running into PEP8 test failures outside of the code I am submitting. I made a few minor adjustments to the code to try and pass the tests, but it seems the PEP8 issues would be best handled in a separate pull request? How would you like to proceed from here?
Thanks for your work on pygeoif!

**Comment by cleder** [comment]
@IanLee1521 : what is your opinion on this?

**Comment by johnpdees** [comment]
Has anyone had a chance to review the new code? What are your thoughts?

**Comment by cleder** [comment]
@johnpdees this is covered with @NormWorthington additions (I think if not please let me know), thanks a lot both of you, this is great :-)

**Comment by johnpdees** [comment]
Thanks! Yes, @NormWorthington included an earlier form of the __repr__ in his PEP8 pull request. This wasn't intentional. The most up-to-date form of the __repr__ is still located in this pull request. However, please hold off on merging this pull request. I am still failing a test for 2.6 compatibility I want to get the code compatible with PYTHON 2.6 first!

**Comment by cleder** [comment]
If you do not need python 2.6, I'd be OK with dropping the support for this version

**Comment by jzmiller1** [comment]
I am in favor of dropping 2.6

**Comment by johnpdees** [comment]
I am in favor of dropping 2.6, as well!

**Comment by IanLee1521** [comment]
If we did want to keep the python 2.6 support, I think we just need to change the format as described in this SO post: http://stackoverflow.com/a/10054232

Namely:

``` python
return("Point({}, {})".format(self.x, self.y))
```

et al, converted to:

``` python
return("Point({0}, {1})".format(self.x, self.y))
```

etc.

**Comment by IanLee1521** [comment]
I just pushed commit IanLee1521/pygeoif@10b7cc9 in my fork which I think fixes the tests.

**Comment by IanLee1521** [comment]
Looks like they do indeed! https://travis-ci.org/IanLee1521/pygeoif/jobs/54666515

**Comment by jzmiller1** [comment]
Everything looks good now!

**Pull request merged**
